# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'iCarTools' do

pod 'SWRevealViewController'
pod 'SBJson', '~> 4.0.0'

end

target 'iCarToolsTests' do

end

